In [12]:
import pandas as pd

data_dir =  "../../Data/positions/"
file_name = "missing_variants_ld.csv"
missing_positions = pd.read_csv(data_dir + file_name)

In [13]:
# Split the position column and add the new columns to the dataframe

missing_positions

     Position          RSID  Chromosome
0   176134882     rs4868701           5
1    91459189    rs10644978           7
2    22861490    rs10764337          10
3   187503758    rs13147907           4
4    44508264    rs58166936           5
5    55970777   rs138866686           3
6    63887449   rs147250346           3
7    52679539   rs199562199           5
8    38583315   rs373038216          22
9    84370124  rs1721204963           4
10   83064195  rs2136866244          12
11  126752992   rs147399132           4

In [ ]:
# Loop through missing_positions 

for index, row in missing_positions.iterrows():
    position = row["Position"]
    chromosome = row["Chromosome"]