In [6]:
# Read the 23andMe raw data file and turn it into a dataframe

import pandas as pd
import numpy as np
import sys

ExampleData = "../genome_Chad_Wrye_v5_Full_20220921063742.txt"
# Read the text file into a DataFrame
ttAndMe = pd.read_csv(ExampleData, sep='\t', comment='#', header=None, names=['rsid', 'chromosome', 'position', 'genotype'])

# Print the DataFrame
print(df)

               rsid chromosome  position genotype
0       rs548049170          1     69869       TT
1         rs9283150          1    565508       AA
2       rs116587930          1    727841       GG
3         rs3131972          1    752721       GG
4        rs12184325          1    754105       CC
...             ...        ...       ...      ...
631993     i4000693         MT     16524        A
631994      i704756         MT     16524        A
631995      i705255         MT     16525        A
631996     i4000757         MT     16526        G
631997      i701671         MT     16526        G

[631998 rows x 4 columns]

/var/folders/yg/982c10113957_2gb06y92y35sx509h/T/ipykernel_42947/2163922483.py:9: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  ttAndMe = pd.read_csv(ExampleData, sep='\t', comment='#', header=None, names=['rsid', 'chromosome', 'position', 'genotype'])

In [8]:
# Read the PRS313.xlsx file into a DataFrame
PRS313 = pd.read_excel('../PRS313.xlsx')


PRS313

,SNPa,Chromosome,Positionb,Reference Allele,Effect Allele,EAFc,Overall Breast Cancerd,ER-positivee,ER-negativef,hybrid ER-positiveg,hybrid ER-negativeh
0,1_100880328_A_T,1,100880328,A,T,0.409678,0.0373,0.0355,0.0160,0.0373,0.0373
1,1_10566215_A_G,1,10566215,A,G,0.329016,-0.0586,-0.0407,-0.1109,-0.0407,-0.1109
2,1_110198129_CAAA_C,1,110198129,CAAA,C,0.775478,0.0458,0.0545,0.0266,0.0458,0.0458
3,1_114445880_G_A,1,114445880,G,A,0.166363,0.0621,0.0642,0.0579,0.0621,0.0621
4,1_118141492_A_C,1,118141492,A,C,0.265682,0.0452,0.0417,0.0551,0.0452,0.0452
...,...,...,...,...,...,...,...,...,...,...,...
308,22_39343916_T_A,22,39343916,T,A,0.254083,0.0407,0.0326,0.0330,0.0407,0.0407
309,22_40904707_CT_C,22,40904707,CT,C,0.109871,0.1148,0.1160,0.1203,0.1148,0.1148
310,22_43433100_C_T,22,43433100,C,T,0.114445,-0.0600,-0.0585,-0.0515,-0.0600,-0.0600
311,22_45319953_G_A,22,45319953,G,A,0.416619,-0.0134,-0.0060,-0.0611,-0.0060,-0.0611
312,22_46283297_G_A,22,46283297,G,A,0.111687,0.0736,0.0719,0.0993,0.0736,0.0736

In [9]:
# Find all the positions in ttAndMe that are in PRS313 by identifying columns with the same position and chromosome

PRS313['in_23andMe'] = PRS313.apply(lambda x: ttAndMe[(ttAndMe['position'] == x['Positionb']) & (ttAndMe['chromosome'] == x['Chromosome'])].shape[0] > 0, axis=1)

In [11]:
PRS313.to_excel('../PRS313_with_23andMe.xlsx', index=False)

63